
PROJECT_SOURCEFILES += spi_master.c
PROJECT_SOURCEFILES += cc2530_spi.c
PROJECT_SOURCEFILES += SFE_LSM9DS0.c

CONTIKI_PROJECT = hello-world 

all: $(CONTIKI_PROJECT) 

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
