clear all;
load('std_0.05_to_0.5_100nodes_100trials.mat');
figure;
x = start_point:0.05:end_point;
hLine = plot(x,error_matrix);
hLine(1).Marker = '*';
hLine(2).Marker = '+';
hLine(3).Marker = 'x';
hLine(4).Marker = 'd';
hLine(5).Marker = 'p';
hLine(6).Marker = '^';
hLine(7).Marker = 'o';
xlabel('Measurement error standard deviation');
ylabel('Relative error');
legend('KI','KK','KK2','DV-distance','N-hop-lateration','IWLSE','CRLB');
