function pretty_polar(mic_data)

    num_angles = size(mic_data, 2);
    
    figure;
    t = 0 : .01 : 2 * pi;
    P = polar(t, max(max(mic_data)) * ones(size(t)));
    set(P, 'Visible', 'off')
    hold on;
    
    t = linspace(0, 360, num_angles+1);
    mic_data = [mic_data, mic_data(:,1)]; % repeat first entry
    h1 = polar(t * pi / 180, mic_data(1,:),'b');
    h2 = polar(t * pi / 180, mic_data(2,:),'r');
    h3 = polar(t * pi / 180, mic_data(3,:),'g');
    
    set(h1, 'Color', [2, 105, 214] ./ 255);
    set(h2, 'Color', [14, 138, 3] ./ 255);
    set(h3, 'Color', [196, 22, 22] ./ 255);
    
    set([h1, h2, h3], 'LineWidth', 2);
    hTitle = title('Polar Microphone Response');
    hLegend = legend([h1, h2, h3], 'Mic A', 'Mic B', 'Mic C');
    set( gca                       , ...
    'FontName'   , 'Helvetica' );
    set([hTitle], ...
        'FontName'   , 'AvantGarde');
    set([hLegend, gca]             , ...
        'FontSize'   , 8           );
    set( hTitle                    , ...
        'FontSize'   , 12          , ...
        'FontWeight' , 'bold'      );

    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'YTick'       , 0:500:2500, ...
      'LineWidth'   , 1         );
end