CONTIKI = ../..

all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors example-powertrace example-broadcast-button \
     example-broadcast-button_rec example-broadcast-button_src example-broadcast-button_src_load \
     example-unicast-button_rec example-unicast-button_src example-unicast-button_src_load example-unicast-button \
     example-broadcast-button_DEBUG example-unicast-button_DEBUG example-broadcast-button_DEBUG_DIST \
     example-unicast-button_DEBUG_DIST example-unicast-button_DEBUG_contention example-broadcast-button_rec_contention \
     example-broadcast-button_DEBUG_content_Initiator example-unicast-button_rec_contention \
     example-runicast example-Runicast example-unicast_Reliable example-unicast-button_contention_src_TEST \
     example-unicast-button_rec_contention_TEST example-broadcast-button_DEBUG_contention

#APPS+=powertrace
#DEFINES=NETSTACK_CONF_RDC=nullrdc_driver  #,NETSTACK_RDC_CHANNEL_CHECK_RATE=2
HAVE_BANKING=1

include $(CONTIKI)/Makefile.include
